In [1]:
import numpy as np

# Linear Algebra in NumPy

NumPy provides a rich set of linear algebra functions in the `numpy.linalg` module. These functions are optimized for matrix operations and solve many common problems in linear algebra.

---

## Key Linear Algebra Operations

### 1. Matrix Multiplication
You can perform matrix multiplication using:
- **`@` operator** (introduced in Python 3.5+)
- **`numpy.dot`** or **`numpy.matmul`**

### 2. Transpose of a Matrix
The transpose of a matrix can be obtained using .T.

### 3. Determinant of a Matrix
Use numpy.linalg.det to calculate the determinant.

### 4. Inverse of a Matrix
Use numpy.linalg.inv to compute the inverse of a square matrix.

### 5. Eigenvalues and Eigenvectors
Use numpy.linalg.eig to compute eigenvalues and eigenvectors.

### 6. Singular Value Decomposition (SVD)
Use numpy.linalg.svd for Singular Value Decomposition.

### 7. Solving a System of Linear Equations
Use numpy.linalg.solve to solve systems of linear equations of the form Ax = B.

### 8. Norm of a Vector or Matrix
Use numpy.linalg.norm to calculate the norm.


In [3]:
mat1 = [[1, 2, 3], [4, 5, 6]]
mat2 = [[7, 8, 9], [10, 11, 12]]

res = np.dot(mat1, mat2)
print(res)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [8]:
mat1 = np.array([[1, 2, 3], [4, 5, 6]]) # matrix of shape 2x3
mat2 = np.array([[7, 8], [10, 11], [9, 12]]) # matrix of shape 3x2

res = np.dot(mat1, mat2)
print(res)
# or operator '@'
res = mat1@mat2
print(res)

# no. of columns in first matrix must be equal to no. of rows in the second matrix.
print(mat1.shape[1] == mat2.shape[0])

[[ 54  66]
 [132 159]]
[[ 54  66]
 [132 159]]
True


In [9]:
# Getting the transpose of a matrix.
print(mat1.T)

[[1 4]
 [2 5]
 [3 6]]
